services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shoplist
      POSTGRES_USER: shoplist_user
      POSTGRES_PASSWORD: shoplist_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: