services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shoplist
      POSTGRES_USER: shoplist_user
      POSTGRES_PASSWORD: shoplist_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shoplist_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shoplist_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shoplist.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - shoplist_network

networks:
  shoplist_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: