name: 'Setup Python Dependencies'
description: 'Sets up Python environment and installs project dependencies with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  install-linting-tools:
    description: 'Whether to install linting tools (flake8, black, mypy)'
    required: false
    default: 'false'
  install-testing-tools:
    description: 'Whether to install testing tools (pytest)'
    required: false
    default: 'false'
  install-system-deps:
    description: 'Whether to install system dependencies for tkinter'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install system dependencies for tkinter
      if: inputs.install-system-deps == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Install Python dependencies
      shell: bash
      env:
        PIP_ROOT_USER_ACTION: ignore
      run: |
        python -m pip install --upgrade pip --root-user-action=ignore
        pip install --root-user-action=ignore -r requirements.txt

    - name: Install linting tools
      if: inputs.install-linting-tools == 'true'
      shell: bash
      env:
        PIP_ROOT_USER_ACTION: ignore
      run: |
        pip install --root-user-action=ignore flake8 black mypy

    - name: Install testing tools
      if: inputs.install-testing-tools == 'true'
      shell: bash
      env:
        PIP_ROOT_USER_ACTION: ignore
      run: |
        pip install --root-user-action=ignore pytest
