name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install system dependencies for tkinter
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with virtual display
      run: |
        # Use xvfb for headless GUI testing
        xvfb-run -a pytest tests/ -v --tb=short
    
    - name: Test module imports
      run: |
        python -c "from src.domain.Product_Entity import _Product; print('✅ Domain imports OK')"
        python -c "from src.utils.list_operations import batch_generator; print('✅ Utils imports OK')"
        python -c "from src.application.usecases.AddProduct import AddProduct; print('✅ UseCase imports OK')"
        python -c "from src.infrastructure.JsonProductRepository import JsonProductRepository; print('✅ Repository imports OK')"
